 #include<stdio.h>
 #include<stdlib.h>
 #include<unistd.h>
 #include<sys/types.h>
 #include<sys/wait.h>
 #include<sys/param.h>
 #include<wait.h>
 #include<sys/stat.h>
 #include<time.h>
 #include<signal.h>
 #include<string.h>
 #include<errno.h>
 #include<fcntl.h>
